### ISSUE TITLE
Add Database Backup Task before Alembic Migrations

### ISSUE THREAD

**Issue by fearnworks** [Open-Model-Initiative/OMI-Data-Pipeline#33]
# Add Database Backup Task Before Alembic Migrations

## Description

We need to implement a database backup mechanism that runs automatically before executing Alembic migrations. This will provide a safety net in case of migration failures or unexpected issues.

## Tasks

1. [ ] Create a backup script that can be called before migrations:
   - Use `pg_dump` to create a backup of the PostgreSQL database
   - Include timestamp in the backup file name
   - Compress the backup file to save space

2. [ ] Modify the Taskfile to include a new task for database backup:
   - Add a `backup-database` task
   - Make this task a dependency for the migration task

3. [ ] Update the migration task to run the backup before executing Alembic commands

4. [ ] Add a restore task to allow easy recovery from backups if needed

5. [ ] Update documentation to reflect these new tasks and the backup process

## Taskfile Additions

```yaml
backup-database:
  cmds:
    - ./backup_database.sh

migrate:
  deps: [backup-database]
  cmds:
    - alembic upgrade head

restore:
  cmds:
    - echo "Implement restore logic here"
```

## Notes

- Ensure that the backup directory has appropriate permissions and sufficient storage space.
- Consider implementing a rotation mechanism for backups to manage disk space over time.

## Related

- Alembic documentation: [https://alembic.sqlalchemy.org/en/latest/](https://alembic.sqlalchemy.org/en/latest/)
- PostgreSQL backup and restore: [https://www.postgresql.org/docs/current/backup.html](https://www.postgresql.org/docs/current/backup.html)
